export const LOTERIAS = [
  { slug: 'tradicional', title: 'Tradicional' },
  { slug: 'tradicional-1-10', title: 'Tradicional 1/10' },
  { slug: 'uruguaia', title: 'Lot. Uruguaia' },
  { slug: 'quininha', title: 'Quininha' },
  { slug: 'seninha', title: 'Seninha' },
  { slug: 'super15', title: 'Super15' },
  { slug: 'repetir-pule', title: 'Repetir Pule' },
];

export const GAME_NAMES = LOTERIAS.reduce((acc, item) => {
  acc[item.slug] = item.title;
  return acc;
}, {});

export const MODALIDADES = [
  'CENTENA',
  'CENTENA INV',
  'CENTENA 3X',
  'CENTENA ESQUERDA',
  'CENTENA INV ESQ',
  'MILHAR',
  'MILHAR INV',
  'MILHAR E CT',
  'UNIDADE',
  'DEZENA',
  'DEZENA ESQ',
  'DEZENA MEIO',
  'DUQUE DEZ',
  'DUQUE DEZ ESQ',
  'DUQUE DEZ MEIO',
  'TERNO DEZ SECO',
  'TERNO DEZ SECO ESQ',
  'TERNO DEZ SECO MEIO',
  'TERNO DEZ',
  'TERNO DEZ ESQ',
  'TERNO DEZ MEIO',
  'GRUPO',
  'GRUPO ESQ',
  'GRUPO MEIO',
  'DUQUE GP',
  'DUQUE GP ESQ',
  'DUQUE GP MEIO',
  'TERNO GP',
  'TERNO GP ESQ',
  'TERNO GP MEIO',
  'QUADRA GP',
  'QUADRA GP ESQ',
  'QUADRA GP MEIO',
  'QUINA GP 8/5',
  'QUINA GP 8/5 ESQ',
  'QUINA GP 8/5 MEIO',
  'SENA GP 10/6',
  'PALPITAO',
  'SENA GP 10/6 ESQ',
  'SENA GP 10/6 MEIO',
  'PASSE VAI',
  'PASSE VAI VEM',
];

export const CAN_CHOOSE_COLOCACAO = [
  'CENTENA',
  'CENTENA INV',
  'CENTENA ESQUERDA',
  'CENTENA INV ESQ',
  'MILHAR',
  'MILHAR INV',
  'MILHAR E CT',
  'UNIDADE',
  'DEZENA',
  'DEZENA ESQ',
  'DEZENA MEIO',
  'GRUPO',
  'GRUPO ESQ',
  'GRUPO MEIO',
];

export const DIRECT_TO_PALPITES = [
  'CENTENA 3X',
  'DUQUE DEZ',
  'DUQUE DEZ ESQ',
  'DUQUE DEZ MEIO',
  'TERNO DEZ SECO',
  'TERNO DEZ SECO ESQ',
  'TERNO DEZ SECO MEIO',
  'TERNO DEZ',
  'TERNO DEZ ESQ',
  'TERNO DEZ MEIO',
  'DUQUE GP ESQ',
  'DUQUE GP MEIO',
  'QUADRA GP',
  'QUADRA GP ESQ',
  'QUADRA GP MEIO',
];

export const COLOCACOES = [
  '1 PREMIO (MAIOR PREMIO)',
  '1/5 (5x MAIS CHANCES)',
  '1 E 1/5 PREMIO',
  '1/2 PREMIO',
  '1/3 PREMIO',
  '1/4 PREMIO',
  '1/5 PREMIO',
  '2/3 PREMIO',
  '2/4 PREMIO',
  '2/5 PREMIO',
  '3/4 PREMIO',
  '3/5 PREMIO',
  '4/5 PREMIO',
];
